export const SET_POKEMONS = "SET_POKEMONS";
export const SET_FAVORITE = "SET_FAVORITE";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const SET_FILTERED_POKEMONS = "SET_FILTERED_POKEMONS";
export const SET_IS_SEARCHING = "SET_IS_SEARCHING";

